//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileReaderTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileReaderTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$id&quot;: &quot;1&quot;,
        ///  &quot;StartTime&quot;: &quot;2014-04-01T00:00:00&quot;,
        ///  &quot;EndTime&quot;: &quot;2014-04-01T23:24:00&quot;,
        ///  &quot;Span&quot;: &quot;23:24:00&quot;,
        ///  &quot;SpanUnits&quot;: 99,
        ///  &quot;UnitSizeInSeconds&quot;: 3.0,
        ///  &quot;ChannelAmountChecksum&quot;: 3,
        ///  &quot;ProgramAmountChecksum&quot;: 837,
        ///  &quot;AdsAmountChecksum&quot;: 1350,
        ///  &quot;TypesOfAds&quot;: {
        ///    &quot;$id&quot;: &quot;2&quot;,
        ///    &quot;141200&quot;: {
        ///      &quot;$id&quot;: &quot;3&quot;,
        ///      &quot;ID&quot;: &quot;141200&quot;
        ///    },
        ///    &quot;060702&quot;: {
        ///      &quot;$id&quot;: &quot;4&quot;,
        ///      &quot;ID&quot;: &quot;060702&quot;
        ///    },
        ///    &quot;011002&quot;: {
        ///      &quot;$id&quot;: &quot;5&quot;,
        ///      &quot;ID&quot;: &quot;011002&quot;
        ///    },
        ///    &quot;161001&quot;: {
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day_3channels_json {
            get {
                return ResourceManager.GetString("day_3channels_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58 32 68
        ///5.5.2014 0:0:0
        ///6.5.2014 0:0:0
        ///%
        ///3
        ///862
        ///1619
        ///%
        ///58
        ///2014-05-04 23:59:48
        ///R 3 bgd 10622 161005 1225 5 4328 644 0.0 0.0
        ///A 38
        ///P 711 bgd 4592.71 0 19525 7492.28 4592.71 0 19525 7492.28
        ///A 33
        ///R 20 bgd 10623 100402 1152 0 3125 441 0.0 0.0
        ///R 15 bgd 10623 111303 896 0 590 554 0.0 0.0
        ///R 30 bgd 10623 141900 1280 0 2953 694 0.0 0.0
        ///R 20 bgd 10623 191103 1152 0 3519 1665 0.0 0.0
        ///R 20 bgd 10623 161007 1152 0 231 1536 0.0 0.0
        ///R 15 bgd 10623 191000 896 0 3499 1665 0.0 0.0
        ///A 64
        ///P 442 bgd 0.0 0 0 0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day_DS_D_DH {
            get {
                return ResourceManager.GetString("day_DS_D_DH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$id&quot;: &quot;1&quot;,
        ///  &quot;StartTime&quot;: &quot;2014-03-05T12:00:00&quot;,
        ///  &quot;EndTime&quot;: &quot;2014-03-05T13:00:00&quot;,
        ///  &quot;Span&quot;: &quot;01:00:00&quot;,
        ///  &quot;SpanUnits&quot;: 73,
        ///  &quot;UnitSizeInSeconds&quot;: 3.0,
        ///  &quot;ChannelAmountChecksum&quot;: 3,
        ///  &quot;ProgramAmountChecksum&quot;: 35,
        ///  &quot;AdsAmountChecksum&quot;: 79,
        ///  &quot;TypesOfAds&quot;: {
        ///    &quot;$id&quot;: &quot;2&quot;,
        ///    &quot;190303&quot;: {
        ///      &quot;$id&quot;: &quot;3&quot;,
        ///      &quot;ID&quot;: &quot;190303&quot;
        ///    },
        ///    &quot;161005&quot;: {
        ///      &quot;$id&quot;: &quot;4&quot;,
        ///      &quot;ID&quot;: &quot;161005&quot;
        ///    },
        ///    &quot;090714&quot;: {
        ///      &quot;$id&quot;: &quot;5&quot;,
        ///      &quot;ID&quot;: &quot;090714&quot;
        ///    },
        ///    &quot;160300&quot;: {
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hour_3channels_json {
            get {
                return ResourceManager.GetString("hour_3channels_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58 32 68
        ///5.5.2014 18:0:0
        ///5.5.2014 19:0:0
        ///%
        ///3
        ///39
        ///101
        ///%
        ///58
        ///2014-05-05 17:59:56
        ///A 7
        ///P 560 bgd 25059.09 12978 28864 5376.16 25059.09 12978 28864 5376.16
        ///A 31
        ///R 30 bgd 10677 050100 1400 0 3412 519 33766.0 33766.0
        ///R 30 bgd 10677 030100 1400 0 3806 572 36217.0 36217.0
        ///R 15 bgd 10677 190301 980 0 3887 575 36203.67 36203.67
        ///R 15 bgd 10677 050101 980 0 2737 1446 39873.5 39873.5
        ///R 15 bgd 10677 160600 980 0 3411 317 39873.5 39873.5
        ///R 15 bgd 10677 011005 980 0 3928 1936 39873.5 39873.5
        ///A 11
        ///P 741 bgd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hour_DS_D_DH {
            get {
                return ResourceManager.GetString("hour_DS_D_DH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58 32 68
        ///5.5.2014 0:0:0
        ///5.6.2014 0:0:0
        ///%
        ///3
        ///26654
        ///51241
        ///%
        ///58
        ///2014-05-04 23:59:48
        ///R 3 bgd 10622 161005 1225 5 4328 644 0.0 0.0
        ///A 38
        ///P 711 bgd 4592.71 0 19525 7492.28 4592.71 0 19525 7492.28
        ///A 33
        ///R 20 bgd 10623 100402 1152 0 3125 441 0.0 0.0
        ///R 15 bgd 10623 111303 896 0 590 554 0.0 0.0
        ///R 30 bgd 10623 141900 1280 0 2953 694 0.0 0.0
        ///R 20 bgd 10623 191103 1152 0 3519 1665 0.0 0.0
        ///R 20 bgd 10623 161007 1152 0 231 1536 0.0 0.0
        ///R 15 bgd 10623 191000 896 0 3499 1665 0.0 0.0
        ///A 64
        ///P 442 bgd 0.0 0 0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string month_DS_D_DH {
            get {
                return ResourceManager.GetString("month_DS_D_DH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$id&quot;: &quot;1&quot;,
        ///  &quot;StartTime&quot;: &quot;2014-01-01T00:00:00&quot;,
        ///  &quot;EndTime&quot;: &quot;2014-01-08T00:00:00&quot;,
        ///  &quot;Span&quot;: &quot;7.00:00:00&quot;,
        ///  &quot;SpanUnits&quot;: 72,
        ///  &quot;UnitSizeInSeconds&quot;: 3.0,
        ///  &quot;ChannelAmountChecksum&quot;: 2,
        ///  &quot;ProgramAmountChecksum&quot;: 2653,
        ///  &quot;AdsAmountChecksum&quot;: 5581,
        ///  &quot;TypesOfAds&quot;: {
        ///    &quot;$id&quot;: &quot;2&quot;,
        ///    &quot;060300&quot;: {
        ///      &quot;$id&quot;: &quot;3&quot;,
        ///      &quot;ID&quot;: &quot;060300&quot;
        ///    },
        ///    &quot;020304&quot;: {
        ///      &quot;$id&quot;: &quot;4&quot;,
        ///      &quot;ID&quot;: &quot;020304&quot;
        ///    },
        ///    &quot;162006&quot;: {
        ///      &quot;$id&quot;: &quot;5&quot;,
        ///      &quot;ID&quot;: &quot;162006&quot;
        ///    },
        ///    &quot;190804&quot;: { [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string week_3channels_json {
            get {
                return ResourceManager.GetString("week_3channels_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58 32 68
        ///5.5.2014 0:0:0
        ///12.5.2014 0:0:0
        ///%
        ///3
        ///6023
        ///11702
        ///%
        ///58
        ///2014-05-04 23:59:48
        ///R 3 bgd 10622 161005 1225 5 4328 644 0.0 0.0
        ///A 38
        ///P 711 bgd 4592.71 0 19525 7492.28 4592.71 0 19525 7492.28
        ///A 33
        ///R 20 bgd 10623 100402 1152 0 3125 441 0.0 0.0
        ///R 15 bgd 10623 111303 896 0 590 554 0.0 0.0
        ///R 30 bgd 10623 141900 1280 0 2953 694 0.0 0.0
        ///R 20 bgd 10623 191103 1152 0 3519 1665 0.0 0.0
        ///R 20 bgd 10623 161007 1152 0 231 1536 0.0 0.0
        ///R 15 bgd 10623 191000 896 0 3499 1665 0.0 0.0
        ///A 64
        ///P 442 bgd 0.0 0 0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string week_DS_D_DH {
            get {
                return ResourceManager.GetString("week_DS_D_DH", resourceCulture);
            }
        }
    }
}
