//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileReaderTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileReaderTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 94 16 4
        ///1.4.2014 0:0:0
        ///1.4.2014 23:23:59
        ///%
        ///3
        ///837
        ///1350
        ///%
        ///94
        ///2014-03-31 23:16:33
        ///P 953 bac 115115.84 73445 176220 23759.58 115115.84 73445 176220 23759.58
        ///A 5
        ///R 30 bac 8402 141200 7800 0 1725 379 97448.0 97448.0
        ///R 15 bac 8402 060702 5460 0 1968 561 97448.0 97448.0
        ///R 10 bac 8402 011002 4290 0 3994 494 97448.0 97448.0
        ///R 30 bac 8402 161001 7800 0 3435 0 99311.33 99311.33
        ///R 30 bac 8402 180300 7800 0 3187 1283 100243.0 100243.0
        ///R 30 bac 8402 001500 7800 0 1566 1082 101174.67 101174.67
        ///R 21 bac 84 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day_3channels {
            get {
                return ResourceManager.GetString("day_3channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$id&quot;: &quot;1&quot;,
        ///  &quot;StartTime&quot;: &quot;2014-04-01T00:00:00&quot;,
        ///  &quot;EndTime&quot;: &quot;2014-04-01T23:23:59&quot;,
        ///  &quot;ChannelAmountChecksum&quot;: 3,
        ///  &quot;ProgramAmountChecksum&quot;: 837,
        ///  &quot;AdsAmountChecksum&quot;: 1350,
        ///  &quot;TypesOfAds&quot;: {
        ///    &quot;$id&quot;: &quot;2&quot;,
        ///    &quot;141200&quot;: {
        ///      &quot;$id&quot;: &quot;3&quot;,
        ///      &quot;ID&quot;: &quot;141200&quot;
        ///    },
        ///    &quot;060702&quot;: {
        ///      &quot;$id&quot;: &quot;4&quot;,
        ///      &quot;ID&quot;: &quot;060702&quot;
        ///    },
        ///    &quot;011002&quot;: {
        ///      &quot;$id&quot;: &quot;5&quot;,
        ///      &quot;ID&quot;: &quot;011002&quot;
        ///    },
        ///    &quot;161001&quot;: {
        ///      &quot;$id&quot;: &quot;6&quot;,
        ///      &quot;ID&quot;: &quot;161001&quot;
        ///    },
        ///    &quot;180300&quot;: {
        ///      &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day_3channels_json {
            get {
                return ResourceManager.GetString("day_3channels_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 51 53
        ///5.3.2014 12:0:0
        ///5.3.2014 13:0:1
        ///%
        ///3
        ///35
        ///79
        ///%
        ///7
        ///2014-03-05 11:59:48
        ///A 28
        ///P 813 idd 0.0 0 0 0.0 0.0 0 0 0.0
        ///A 45
        ///R 45 idd 5176 190303 525 0 3886 575 0.0 0.0
        ///R 30 idd 5176 161005 350 0 252 1269 0.0 0.0
        ///R 30 idd 5176 090714 350 0 3904 1875 0.0 0.0
        ///R 30 idd 5176 160300 350 0 3437 0 0.0 0.0
        ///R 30 idd 5176 111301 350 0 2577 66 0.0 0.0
        ///R 30 idd 5176 161504 350 0 4169 480 0.0 0.0
        ///R 15 idd 5176 190900 245 0 3850 1566 0.0 0.0
        ///A 40
        ///P 431 idd 0.0 0 0 0.0 0.0 0 0 0.0
        ///A 20
        ///R 90 idd 5177 050104 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hour_3channels {
            get {
                return ResourceManager.GetString("hour_3channels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$id&quot;: &quot;1&quot;,
        ///  &quot;StartTime&quot;: &quot;2014-03-05T12:00:00&quot;,
        ///  &quot;EndTime&quot;: &quot;2014-03-05T13:00:01&quot;,
        ///  &quot;ChannelAmountChecksum&quot;: 3,
        ///  &quot;ProgramAmountChecksum&quot;: 35,
        ///  &quot;AdsAmountChecksum&quot;: 79,
        ///  &quot;TypesOfAds&quot;: {
        ///    &quot;$id&quot;: &quot;2&quot;,
        ///    &quot;190303&quot;: {
        ///      &quot;$id&quot;: &quot;3&quot;,
        ///      &quot;ID&quot;: &quot;190303&quot;
        ///    },
        ///    &quot;161005&quot;: {
        ///      &quot;$id&quot;: &quot;4&quot;,
        ///      &quot;ID&quot;: &quot;161005&quot;
        ///    },
        ///    &quot;090714&quot;: {
        ///      &quot;$id&quot;: &quot;5&quot;,
        ///      &quot;ID&quot;: &quot;090714&quot;
        ///    },
        ///    &quot;160300&quot;: {
        ///      &quot;$id&quot;: &quot;6&quot;,
        ///      &quot;ID&quot;: &quot;160300&quot;
        ///    },
        ///    &quot;111301&quot;: {
        ///      &quot;$id [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hour_3channels_json {
            get {
                return ResourceManager.GetString("hour_3channels_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 94 21
        ///1.1.2014 0:0:0
        ///7.1.2014 23:59:59
        ///%
        ///2
        ///2653
        ///5581
        ///%
        ///94
        ///2014-01-01 00:50:26
        ///R 8 dab 1 060300 13250 4 2976 1802 713040.5 586577.55
        ///R 8 dab 1 020304 13250 4 530 54 713040.5 586577.55
        ///A 5
        ///R 30 dab 2 162006 26500 5 577 577 704018.0 578777.72
        ///R 20 dab 2 190804 23850 5 2553 1885 698552.5 574877.81
        ///R 30 dab 2 180300 26500 5 814 996 690280.0 573005.09
        ///R 20 dab 2 040700 23850 5 3522 1665 679854.0 566218.86
        ///R 15 dab 2 180101 18550 5 4176 1711 679854.0 566218.86
        ///R 15 dab 2 180105 18550 5 4178 1711  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string week_3channel {
            get {
                return ResourceManager.GetString("week_3channel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$id&quot;: &quot;1&quot;,
        ///  &quot;StartTime&quot;: &quot;2014-01-01T00:00:00&quot;,
        ///  &quot;EndTime&quot;: &quot;2014-01-07T23:59:59&quot;,
        ///  &quot;ChannelAmountChecksum&quot;: 2,
        ///  &quot;ProgramAmountChecksum&quot;: 2653,
        ///  &quot;AdsAmountChecksum&quot;: 5581,
        ///  &quot;TypesOfAds&quot;: {
        ///    &quot;$id&quot;: &quot;2&quot;,
        ///    &quot;060300&quot;: {
        ///      &quot;$id&quot;: &quot;3&quot;,
        ///      &quot;ID&quot;: &quot;060300&quot;
        ///    },
        ///    &quot;020304&quot;: {
        ///      &quot;$id&quot;: &quot;4&quot;,
        ///      &quot;ID&quot;: &quot;020304&quot;
        ///    },
        ///    &quot;162006&quot;: {
        ///      &quot;$id&quot;: &quot;5&quot;,
        ///      &quot;ID&quot;: &quot;162006&quot;
        ///    },
        ///    &quot;190804&quot;: {
        ///      &quot;$id&quot;: &quot;6&quot;,
        ///      &quot;ID&quot;: &quot;190804&quot;
        ///    },
        ///    &quot;180300&quot;: {
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string week_3channels_json {
            get {
                return ResourceManager.GetString("week_3channels_json", resourceCulture);
            }
        }
    }
}
