//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileReaderTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileReaderTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 94 21
        ///1.1.2014 0:0:0
        ///7.1.2014 23:59:59
        ///%
        ///2
        ///2653
        ///5581
        ///%
        ///94
        ///2014-01-01 00:50:26
        ///R 8 dab 1 060300 13250 4 2976 1802 713040.5 586577.55
        ///R 8 dab 1 020304 13250 4 530 54 713040.5 586577.55
        ///A 5
        ///R 30 dab 2 162006 26500 5 577 577 704018.0 578777.72
        ///R 20 dab 2 190804 23850 5 2553 1885 698552.5 574877.81
        ///R 30 dab 2 180300 26500 5 814 996 690280.0 573005.09
        ///R 20 dab 2 040700 23850 5 3522 1665 679854.0 566218.86
        ///R 15 dab 2 180101 18550 5 4176 1711 679854.0 566218.86
        ///R 15 dab 2 180105 18550 5 4178 1711  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3_channel_week {
            get {
                return ResourceManager.GetString("_3_channel_week", resourceCulture);
            }
        }
    }
}
