//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SystemTestsProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SystemTestsProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$id&quot;: &quot;1&quot;,
        ///  &quot;BrandConflictMatrix&quot;: {
        ///    &quot;$id&quot;: &quot;2&quot;,
        ///    &quot;519&quot;: {
        ///      &quot;$id&quot;: &quot;3&quot;,
        ///      &quot;554&quot;: 0.0,
        ///      &quot;1761&quot;: 0.0,
        ///      &quot;1936&quot;: 0.0,
        ///      &quot;846&quot;: 0.0,
        ///      &quot;358&quot;: 0.0,
        ///      &quot;1774&quot;: 0.0,
        ///      &quot;337&quot;: 0.0,
        ///      &quot;63&quot;: 0.0,
        ///      &quot;1260&quot;: 0.0,
        ///      &quot;1446&quot;: 0.0,
        ///      &quot;1873&quot;: 0.0,
        ///      &quot;1082&quot;: 0.0,
        ///      &quot;1283&quot;: 0.0,
        ///      &quot;540&quot;: 0.0,
        ///      &quot;1203&quot;: 0.0,
        ///      &quot;645&quot;: 0.0,
        ///      &quot;467&quot;: 0.0,
        ///      &quot;1724&quot;: 0.0,
        ///      &quot;845&quot;: 0.0,
        ///      &quot;481&quot;: 0.0,
        ///      &quot;246&quot;: 0.0,
        ///      &quot;1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day_3channels_json {
            get {
                return ResourceManager.GetString("day_3channels_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58 32 68
        ///5.5.2014 0:0:0
        ///6.5.2014 0:0:0
        ///%
        ///3
        ///862
        ///1619
        ///%
        ///58
        ///2014-05-04 23:59:48
        ///R 3 bgd 10622 161005 1225 5 4328 644 0.0 0.0
        ///A 38
        ///P 711 bgd 4592.71 0 19525 7492.28 4592.71 0 19525 7492.28
        ///A 33
        ///R 20 bgd 10623 100402 1152 0 3125 441 0.0 0.0
        ///R 15 bgd 10623 111303 896 0 590 554 0.0 0.0
        ///R 30 bgd 10623 141900 1280 0 2953 694 0.0 0.0
        ///R 20 bgd 10623 191103 1152 0 3519 1665 0.0 0.0
        ///R 20 bgd 10623 161007 1152 0 231 1536 0.0 0.0
        ///R 15 bgd 10623 191000 896 0 3499 1665 0.0 0.0
        ///A 64
        ///P 442 bgd 0.0 0 0 0.0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string day_DS_D_DH {
            get {
                return ResourceManager.GetString("day_DS_D_DH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$id&quot;: &quot;1&quot;,
        ///  &quot;BrandConflictMatrix&quot;: {
        ///    &quot;$id&quot;: &quot;2&quot;,
        ///    &quot;575&quot;: {
        ///      &quot;$id&quot;: &quot;3&quot;,
        ///      &quot;1446&quot;: 0.0,
        ///      &quot;572&quot;: 0.0,
        ///      &quot;1296&quot;: 0.0,
        ///      &quot;554&quot;: 0.0,
        ///      &quot;1283&quot;: 0.0,
        ///      &quot;337&quot;: 1.0,
        ///      &quot;575&quot;: 1.0,
        ///      &quot;317&quot;: 1.0,
        ///      &quot;1305&quot;: 1.0,
        ///      &quot;1538&quot;: 1.0,
        ///      &quot;1973&quot;: 1.0,
        ///      &quot;1082&quot;: 1.0,
        ///      &quot;519&quot;: 1.0
        ///    },
        ///    &quot;1446&quot;: {
        ///      &quot;$id&quot;: &quot;4&quot;,
        ///      &quot;575&quot;: 0.0,
        ///      &quot;317&quot;: 0.0,
        ///      &quot;337&quot;: 0.0,
        ///      &quot;572&quot;: 1.0,
        ///      &quot;1446&quot;: 1.0,
        ///      &quot;1296&quot;: 1.0,
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hour_3channels_json {
            get {
                return ResourceManager.GetString("hour_3channels_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58 32 68
        ///5.5.2014 18:0:0
        ///5.5.2014 19:0:0
        ///%
        ///3
        ///39
        ///101
        ///%
        ///58
        ///2014-05-05 17:59:56
        ///A 7
        ///P 560 bgd 25059.09 12978 28864 5376.16 25059.09 12978 28864 5376.16
        ///A 31
        ///R 30 bgd 10677 050100 1400 0 3412 519 33766.0 33766.0
        ///R 30 bgd 10677 030100 1400 0 3806 572 36217.0 36217.0
        ///R 15 bgd 10677 190301 980 0 3887 575 36203.67 36203.67
        ///R 15 bgd 10677 050101 980 0 2737 1446 39873.5 39873.5
        ///R 15 bgd 10677 160600 980 0 3411 317 39873.5 39873.5
        ///R 15 bgd 10677 011005 980 0 3928 1936 39873.5 39873.5
        ///A 11
        ///P 741 bgd [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string hour_DS_D_DH {
            get {
                return ResourceManager.GetString("hour_DS_D_DH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$id&quot;: &quot;1&quot;,
        ///  &quot;BrandConflictMatrix&quot;: {
        ///    &quot;$id&quot;: &quot;2&quot;,
        ///    &quot;607&quot;: {
        ///      &quot;$id&quot;: &quot;3&quot;,
        ///      &quot;1&quot;: 0.0,
        ///      &quot;1487&quot;: 0.0,
        ///      &quot;1761&quot;: 0.0,
        ///      &quot;1484&quot;: 0.0,
        ///      &quot;1283&quot;: 0.0,
        ///      &quot;577&quot;: 0.0,
        ///      &quot;1235&quot;: 0.0,
        ///      &quot;1568&quot;: 0.0,
        ///      &quot;540&quot;: 0.0,
        ///      &quot;955&quot;: 0.0,
        ///      &quot;1082&quot;: 0.0,
        ///      &quot;235&quot;: 0.0,
        ///      &quot;1885&quot;: 0.0,
        ///      &quot;2085&quot;: 0.0,
        ///      &quot;1023&quot;: 0.0,
        ///      &quot;1499&quot;: 0.0,
        ///      &quot;607&quot;: 0.0,
        ///      &quot;142&quot;: 0.0,
        ///      &quot;815&quot;: 0.0,
        ///      &quot;572&quot;: 0.0,
        ///      &quot;1305&quot;: 0.0,
        ///      &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string month_3channels_json {
            get {
                return ResourceManager.GetString("month_3channels_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58 32 68
        ///5.5.2014 0:0:0
        ///5.6.2014 0:0:0
        ///%
        ///3
        ///26654
        ///51241
        ///%
        ///58
        ///2014-05-04 23:59:48
        ///R 3 bgd 10622 161005 1225 5 4328 644 0.0 0.0
        ///A 38
        ///P 711 bgd 4592.71 0 19525 7492.28 4592.71 0 19525 7492.28
        ///A 33
        ///R 20 bgd 10623 100402 1152 0 3125 441 0.0 0.0
        ///R 15 bgd 10623 111303 896 0 590 554 0.0 0.0
        ///R 30 bgd 10623 141900 1280 0 2953 694 0.0 0.0
        ///R 20 bgd 10623 191103 1152 0 3519 1665 0.0 0.0
        ///R 20 bgd 10623 161007 1152 0 231 1536 0.0 0.0
        ///R 15 bgd 10623 191000 896 0 3499 1665 0.0 0.0
        ///A 64
        ///P 442 bgd 0.0 0 0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string month_DS_D_DH {
            get {
                return ResourceManager.GetString("month_DS_D_DH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;$id&quot;: &quot;1&quot;,
        ///  &quot;BrandConflictMatrix&quot;: {
        ///    &quot;$id&quot;: &quot;2&quot;,
        ///    &quot;607&quot;: {
        ///      &quot;$id&quot;: &quot;3&quot;,
        ///      &quot;1&quot;: 0.0,
        ///      &quot;577&quot;: 0.0,
        ///      &quot;1761&quot;: 0.0,
        ///      &quot;1235&quot;: 0.0,
        ///      &quot;1043&quot;: 0.0,
        ///      &quot;142&quot;: 0.0,
        ///      &quot;1960&quot;: 0.0,
        ///      &quot;1568&quot;: 0.0,
        ///      &quot;955&quot;: 0.0,
        ///      &quot;648&quot;: 0.0,
        ///      &quot;1499&quot;: 0.0,
        ///      &quot;218&quot;: 0.0,
        ///      &quot;1875&quot;: 0.0,
        ///      &quot;1484&quot;: 0.0,
        ///      &quot;1023&quot;: 0.0,
        ///      &quot;1692&quot;: 0.0,
        ///      &quot;2085&quot;: 0.0,
        ///      &quot;845&quot;: 0.0,
        ///      &quot;1972&quot;: 0.0,
        ///      &quot;235&quot;: 0.0,
        ///      &quot;519&quot;: 0.0,
        ///      &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string week_3channels_json {
            get {
                return ResourceManager.GetString("week_3channels_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 58 32 68
        ///5.5.2014 0:0:0
        ///12.5.2014 0:0:0
        ///%
        ///3
        ///6023
        ///11702
        ///%
        ///58
        ///2014-05-04 23:59:48
        ///R 3 bgd 10622 161005 1225 5 4328 644 0.0 0.0
        ///A 38
        ///P 711 bgd 4592.71 0 19525 7492.28 4592.71 0 19525 7492.28
        ///A 33
        ///R 20 bgd 10623 100402 1152 0 3125 441 0.0 0.0
        ///R 15 bgd 10623 111303 896 0 590 554 0.0 0.0
        ///R 30 bgd 10623 141900 1280 0 2953 694 0.0 0.0
        ///R 20 bgd 10623 191103 1152 0 3519 1665 0.0 0.0
        ///R 20 bgd 10623 161007 1152 0 231 1536 0.0 0.0
        ///R 15 bgd 10623 191000 896 0 3499 1665 0.0 0.0
        ///A 64
        ///P 442 bgd 0.0 0 0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string week_DS_D_DH {
            get {
                return ResourceManager.GetString("week_DS_D_DH", resourceCulture);
            }
        }
    }
}
